const products = [
  {
    id: 1,
    name: "chex T-shirt",
    price: "500",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/1.png",
  },
  {
    id: 2,
    name: "primeum T-shirt",
    price: "300",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/2.png",
  },
  {
    id: 3,
    name: "jursey",
    price: "500",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/3.jpg",
  },
  {
    id: 4,
    name: "black udhi",
    price: "500",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/4.jpg",
  },
  {
    id: 5,
    name: "Faded jeans",
    price: "200",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/5.jpg",
  },
  {
    id: 6,
    name: "leather overwear",
    price: "800",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/6.jpg",
  },
  {
    id: 7,
    name: "stylies shirt",
    price: "200",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/7.jpg",
  },
  {
    id: 8,
    name: "Faded huddi",
    price: "350",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/8.jpg",
  },
  {
    id: 9,
    name: "basic uddhi",
    price: "400",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/9.jpg",
  },
  {
    id: 10,
    name: "Spider cap",
    price: "400",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/10.jpg",
  },
  {
    id: 11,
    name: "flame premium",
    price: "400",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/11.jpg",
  },
  {
    id: 12,
    name: "premium White cap",
    price: "250",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/12.jpg",
  },
  {
    id: 13,
    name: "premium dragon cap",
    price: "700",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/13.jpg",
  },
  {
    id: 14,
    name: "ride mask",
    price: "1000",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/14.jpg",
  },
  {
    id: 15,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/15.jpg",
  },
  {
    id: 16,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/16.jpg",
  },
  {
    id: 17,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/16.jpg",
  },
  {
    id: 18,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/16.jpg",
  },
  {
    id: 19,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/16.jpg",
  },
  {
    id: 20,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/16.jpg",
  },
  {
    id: 21,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/17.jpg",
  },
  {
    id: 22,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/18.jpg",
  },
  {
    id: 23,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/19.jpg",
  },
  {
    id: 24,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/20.jpg",
  },
  {
    id: 25,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/21.jpg",
  },
  {
    id: 26,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/22.jpg",
  },
  {
    id: 27,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
  },
  {
    id: 28,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
  },
  {
    id: 29,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
  },
  {
    id: 30,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
  },
  {
    id: 31,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
  },
  {
    id: 32,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
  },
  {
    id: 33,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
  },
  {
    id: 34,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
  },
  {
    id: 33,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
  },
  {
    id: 35,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/24.jpg",
  },
  {
    id: 36,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/25.jpg",
  },
  {
    id: 37,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/26.jpg",
  },
  {
    id: 38,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/27.jpg",
  },
  {
    id: 39,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/28.jpg",
  },
  {
    id: 40,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/29.jpg",
  },
];
export default products;
