const products = [
  {
    id: 1,
    name:"Grey Lounge chair",
    price: "500",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/1.png",
  },
  {
    id: 2,
    name:"Goldish Lounge chair",
    price: "300",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/2.png",
  },
  {
    id: 3,
    name:"off white Lounge chair",
    price: "500",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/3.png",
  },
  {
    id: 4,
    name:"brown chair",
    price: "500",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/4.png",
  },
  {
    id: 5,
    name:"decent light green chair",
    price: "200",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/5.png",
  },
  {
    id: 6,
    name:"leader dark green chair",
    price: "800",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/6.png",
  },
  {
    id: 7,
    name:"steel chair",
    price: "200",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/7.png",
  },
  {
    id: 8,
    name:"wooden chair",
    price: "350",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/8.png",
  },
  {
    id: 9,
    name:"basic white chair",
    price: "400",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/9.png",
  },
  {
    id: 10,
    name:"basic purple chair",
    price: "400",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/10.png",
  },
  {
    id: 11,
    name:"garden chair",
    price: "400",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/11.png",
  },
  {
    id: 12,
    name:"non handle chair",
    price: "250",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/12.png",
  },
  {
    id: 13,
    name:"office chair",
    price: "700",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/13.png",
  },
  {
    id: 14,
    name:"boss chair",
    price: "1000",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/14.png",
  },
  {
    id: 15,
    name:"hall chair",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/15.png",
  },
];
export default products;
