const products = [
  {
    id: 1,
    name: "Urban Pulse",
    price: "500",
    description: "Discover bold streetwear that blends comfort with cutting-edge design. Stand out with vibrant colors and iconic patterns crafted for trendsetters. Upgrade your wardrobe with styles that make every move iconic.",
    image: "images/1.png",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 2,
    name: "Street Luxe Drop",
    price: "300",
    description: "Something iconic is on the way—get ready for our latest fashion drop. Coming soon: bold streetwear meets effortless luxury. Fresh styles, modern attitude. Stay tuned for the next big release. Prepare for the drop—urban fashion redefined. New vibes loading… your next style upgrade is almost here.",
    image: "images/2.png",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 3,
    name: "Retro Varsity Vibes",
    price: "500",
    description: "A classic oversized varsity jersey reimagined for modern streetwear. Featuring bold “43” graphics, layered styling, and a vintage color palette, this piece blends sporty energy with casual urban cool. Perfect for effortless everyday fits that stand out.",
    image: "images/3.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 4,
    name: "Denim Script",
    price: "500",
    description: "A standout denim jacket with bold script embroidery across the back, merging street culture with timeless craftsmanship. Paired with a striped knit beanie, this look delivers effortless cool and individuality—perfect for those who want their outfit to speak louder than words.",
    image: "images/4.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 5,
    name: "“Reaven Inferno Denim",
    price: "200",
    description: "Crafted in Italy, the Reaven Inferno Denim features 3D embroidered flame motifs and bold gothic “Reaven” back pocket detailing. A fusion of luxury craftsmanship and rebellious streetwear energy, these jeans redefine statement denim with raw edge finishes and powerful design.",
    image: "images/5.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 6,
    name: "Crusader Leather Jacket",
    price: "8000",
    description: "The Crusader Leather Jacket fuses luxury craftsmanship with bold gothic edge. Made from premium black leather and detailed with striking white cross patches, it is a statement piece that balances timeless style with rebellious streetwear energy. Designed to stand out, this jacket elevates any fit into an iconic look.",
    image: "images/6.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 7,
    name: "Rustic Rebel Patchwork Shirt",
    price: "120 ",
    description: "The Rustic Rebel Patchwork Shirt blends vintage aesthetics with modern streetwear energy. Designed with contrasting plaid and corduroy panels, raw distressed edges, and a rugged finish, this piece stands as a statement of individuality. Perfect for layering or wearing solo, it captures a raw, deconstructed vibe that is both stylish and unapologetic.",
    image: "images/7.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 8,
    name: "Eclipse Gradient Jacket",
    price: "160 ",
    description: "The Eclipse Gradient Jacket merges bold design with sleek streetwear aesthetics. Featuring a smooth black-to-white gradient fade, structured silhouette, and subtle embroidered details, this piece is built to stand out. Lightweight yet striking, it is the perfect statement jacket for layering across seasons while keeping your fit elevated and unique.",
    image: "images/8.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 9,
    name: "NY Casual Co-ord Set",
    price: "1899 ",
    description: "Step out in style with this NY beige co-ord set, featuring a button-up shirt and matching shorts. Designed for comfort and casual outings, it's lightweight, breathable, and trendy—perfect for a streetwear vibe.",
    image: "images/9.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 10,
    name: "Adventure Lion Graphic Tee & Shorts Set",
    price: "42.99",
    description: " :Quality Materials: Organic cotton, recycled insulation, water-resistant fabrics Inclusive Sizing: XS-XXL options across products Versatile Styling: Layering pieces for year-round wear Value Focus: Bundle deals and premium construction at accessible prices Care Instructions: Clear maintenance notes for longevity All products",
    image: "images/10.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 11,
    name: "Striped Sweater & Bow Shorts Combo",
    price: "38.99",
    description: "Adorable and playful, this children's set includes a cozy white long-sleeve sweater with vibrant red, black, and white stripes and whimsical handwritten-style text. Complemented by red shorts featuring a charming white bow detail, and completed with sporty black/red/white sneakers, this outfit keeps your little one stylish and comfortable for playdates or family outings.",
    image: "images/11.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 12,
    name: "premium White cap",
    price: "250",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/12.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 13,
    name: "premium dragon cap",
    price: "700",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/13.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 14,
    name: "ride mask",
    price: "1000",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/14.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 15,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/15.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 16,
    name: "Adventure Lion Graphic Tee & Shorts Set",
    price: "370",
    description: "Embrace your wild side with this casual khaki tee and shorts set. The short-sleeve T-shirt features a bold lion graphic and 'ADVENTURE' text for a rugged, outdoorsy vibe. Paired with sleek black shorts, this set offers effortless style for weekend outings or relaxed hangouts. Hang it on your closet rack for easy access to instant adventure-ready looks!",
    image: "images/16.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 17,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/17.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 18,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/18.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 19,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/19.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 20,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/20.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 21,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/21.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 22,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/22.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 23,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/23.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 24,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/24.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 25,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/25.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 26,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/26.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 27,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/27.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 28,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/28.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 29,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/29.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 30,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/30.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 31,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/31.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 32,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/32.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 33,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/33.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 34,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/34.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 35,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/35.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 36,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/36.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 37,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/37.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 38,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/38.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 39,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/39.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 40,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/40.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 41,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/41.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 42,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/42.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 43,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/43.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 44,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/44.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 44,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/44.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 45,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/45.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 46,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/46.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 47,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/47.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 48,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/48.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 49,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/49.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 50,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/50.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 51,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/51.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 52,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/52.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 53,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/53.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 54,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/54.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 55,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/55.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 56,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/56.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 57,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/57.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 58,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/58.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 59,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/59.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 60,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/60.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 61,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/61.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 62,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/62.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 63,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/63.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 64,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/64.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 65,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/65.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 66,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/66.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 67,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/67.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 68,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/68.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 69,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/69.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
  {
    id: 70,
    name: "premium Blue flame",
    price: "370",
    description: "Expertly rendered by Carl hansen & son",
    image: "images/70.jpg",
    Ship:"UPDATE OF SHIPMENT : : within 24 hours. Free returns on orders over $50.",
  },
];
export default products;
